final: main.o dirTree.o fileInfo.o refArray.o strShare.o termFind.o
	gcc -Wall main.o dirTree.o fileInfo.o refArray.o strShare.o termFind.o -o final

dirTree.o: dirTree.c dirTree.h
	gcc -c dirTree.c dirTree.h

fileInfo.o: fileInfo.c fileInfo.h
	gcc -c fileInfo.c fileInfo.h

refArray.o: refArray.c refArray.h
	gcc -c refArray.c refArray.h

strShare.o: strShare.c strShare.h
	gcc -c strShare.c strShare.h

termFind.o: termFind.c termFind.h
	gcc -c termFind.c termFind.h