final.out: main.o dirTree.o fileInfo.o refArray.o strShare.o termFind.o
	gcc -Wall main.o dirTree.o fileInfo.o refArray.o strShare.o termFind.o

dirTree.o: dirTree.c dirTree.h
	gcc -c dirTree.c dirTree.h

fileInfo: fileInfo.c fileInfo.h
	gcc -c fileInfo.c fileInfo.h

refArray: refArray.c refArray.h
	gcc -c refArray.c refArray.h

strShare: strShare.c strShare.h
	gcc -c strShare.c strShare.h

termFind: termFind.c termFind.h
	gcc -c termFind.c termFind.h