a.out: demo-vector-str.o vector-str.o
	gcc demo-vector-str.o vector-str.o

demo-vector-str.o: demo-vector-str.c vector-str.h
	gcc -c demo-vector-str.c


vector-str.o: vector-str.c vector-str.h
	gcc -c vector-str.c

